#!/bin/bash -x

# graphe : INFRA PROJECT LAB

# create different namespaces
ip netns add routA
ip netns add routB
ip netns add rout1
ip netns add rout2
ip netns add poste1
ip netns add poste2
ip netns add poste3
ip netns add poste4

# create the switches
ovs-vsctl add-br internet
ovs-vsctl add-br resB
ovs-vsctl add-br resC
ovs-vsctl add-br resD
ovs-vsctl add-br resE

# configurer routA
ip link add routA-eth0 type veth peer name resC-routA
ip link add routA-eth1 type veth peer name internet-routA
ip link set routA-eth0 netns routA
ip link set routA-eth1 netns routA
ovs-vsctl add-port resC resC-routA
ip link set dev resC-routA up
ovs-vsctl add-port internet internet-routA
ip link set dev internet-routA up
ip netns exec routA ip link set dev lo up
ip netns exec routA ip link set dev routA-eth0 up
ip netns exec routA ip link set dev routA-eth1 up
ip netns exec routA ip a add dev routA-eth0 172.16.1.254/24
ip netns exec routA ip a add dev routA-eth1 10.87.0.1/24
ip netns exec routA ip r add 172.16.2.0/24 via 10.87.0.2 dev routA-eth1
ip netns exec routA sysctl net.ipv4.conf.all.forwarding=1

# configurer routB
ip link add routB-eth0 type veth peer name resB-routB
ip link add routB-eth1 type veth peer name internet-routB
ip link set routB-eth0 netns routB
ip link set routB-eth1 netns routB
ovs-vsctl add-port resB resB-routB
ip link set dev resB-routB up
ovs-vsctl add-port internet internet-routB
ip link set dev internet-routB up
ip netns exec routB ip link set dev lo up
ip netns exec routB ip link set dev routB-eth0 up
ip netns exec routB ip link set dev routB-eth1 up
ip netns exec routB ip a add dev routB-eth0 172.16.2.254/24
ip netns exec routB ip a add dev routB-eth1 10.87.0.2/24
ip netns exec routB ip r add 172.16.1.0/24 via 10.87.0.1 dev routB-eth1
ip netns exec routB sysctl net.ipv4.conf.all.forwarding=1

# configurer rout1
ip link add rout1-eth0 type veth peer name resC-rout1
ip link add rout1-eth1 type veth peer name resD-rout1
ip link set rout1-eth0 netns rout1
ip link set rout1-eth1 netns rout1
ovs-vsctl add-port resC resC-rout1
ovs-vsctl add-port resD resD-rout1 trunks=100,200
ip link set dev resC-rout1 up
ip link set dev resD-rout1 up
ip netns exec rout1 ip link set dev lo up
ip netns exec rout1 ip link set dev rout1-eth0 up
ip netns exec rout1 ip link set dev rout1-eth1 up
ip netns exec rout1 ip a add dev rout1-eth0 172.16.1.253/24
ip netns exec rout1 ip r add 10.87.0.0/24 via 172.16.1.254 dev rout1-eth0
ip netns exec rout1 ip r add 172.16.2.0/24 via 172.16.1.254 dev rout1-eth0
ip netns exec rout1 sysctl net.ipv4.conf.all.forwarding=1

# configurer rout2
ip link add rout2-eth0 type veth peer name resB-rout2
ip link add rout2-eth1 type veth peer name resE-rout2
ip link set rout2-eth0 netns rout2
ip link set rout2-eth1 netns rout2
ovs-vsctl add-port resB resB-rout2
ovs-vsctl add-port resE resE-rout2 trunks=100,200
ip link set dev resB-rout2 up
ip link set dev resE-rout2 up
ip netns exec rout2 ip link set dev lo up
ip netns exec rout2 ip link set dev rout2-eth0 up
ip netns exec rout2 ip link set dev rout2-eth1 up
ip netns exec rout2 ip a add dev rout2-eth0 172.16.2.253/24
ip netns exec rout2 ip r add 10.87.0.0/24 via 172.16.2.254 dev rout2-eth0
ip netns exec rout2 ip r add 172.16.1.0/24 via 172.16.2.254 dev rout2-eth0
ip netns exec rout2 sysctl net.ipv4.conf.all.forwarding=1

# configure poste1
ip link add poste1-eth0 type veth peer name resE-poste1
ip link set poste1-eth0 netns poste1
ip netns exec poste1 ip link set dev poste1-eth0 address 00:11:22:00:01:00
ovs-vsctl add-port resE resE-poste1 tag=100
ip link set dev resE-poste1 up
ip netns exec poste1 ip link set dev lo up
ip netns exec poste1 ip link set dev poste1-eth0 up
ip netns exec poste1 ip a add dev poste1-eth0 192.168.100.1/24
ip netns exec poste1 ip r add default dev poste1-eth0 via 192.168.100.254

# configure poste2
ip link add poste2-eth0 type veth peer name resE-poste2
ip link set poste2-eth0 netns poste2
ip netns exec poste2 ip link set dev poste2-eth0 address 00:11:22:00:02:00
ovs-vsctl add-port resE resE-poste2 tag=200
ip link set dev resE-poste2 up
ip netns exec poste2 ip link set dev lo up
ip netns exec poste2 ip link set dev poste2-eth0 up
ip netns exec poste2 ip a add dev poste2-eth0 192.168.200.1/24
ip netns exec poste2 ip r add default dev poste2-eth0 via 192.168.200.254

# configure poste3
ip link add poste3-eth0 type veth peer name resD-poste3
ip link set poste3-eth0 netns poste3
ip netns exec poste3 ip link set dev poste3-eth0 address 00:11:22:00:03:00
ovs-vsctl add-port resD resD-poste3 tag=100
ip link set dev resD-poste3 up
ip netns exec poste3 ip link set dev lo up
ip netns exec poste3 ip link set dev poste3-eth0 up
ip netns exec poste3 ip a add dev poste3-eth0 192.168.100.2/24
ip netns exec poste3 ip r add default dev poste3-eth0 via 192.168.100.254

# configure poste4 
ip link add poste4-eth0 type veth peer name resD-poste4
ip link set poste4-eth0 netns poste4
ip netns exec poste4 ip link set dev poste4-eth0 address 00:11:22:00:04:00
ovs-vsctl add-port resD resD-poste4 tag=200
ip link set dev resD-poste4 up
ip netns exec poste4 ip link set dev lo up
ip netns exec poste4 ip link set dev poste4-eth0 up
ip netns exec poste4 ip a add dev poste4-eth0 192.168.200.2/24
ip netns exec poste4 ip r add default dev poste4-eth0 via 192.168.200.254

# Config tunnel rout1
ip netns exec rout1 ip l2tp add tunnel remote 172.16.2.253 local 172.16.1.253 encap ip tunnel_id 3000 peer_tunnel_id 4000
ip netns exec rout1 ip l2tp add session tunnel_id 3000 session_id 1000 peer_session_id 2000
ip netns exec rout1 ip link set l2tpeth0 up
ip netns exec rout1 ip a flush dev rout1-eth1
ip netns exec rout1 brctl addbr tunnel
ip netns exec rout1 brctl addif tunnel l2tpeth0
ip netns exec rout1 brctl addif tunnel rout1-eth1
ip netns exec rout1 ip link set tunnel up
ip netns exec rout1 ip link add link tunnel name tunnel.100 type vlan id 100
ip netns exec rout1 ip link set tunnel.100 up
ip netns exec rout1 ip link add link tunnel name tunnel.200 type vlan id 200
ip netns exec rout1 ip link set tunnel.200 up
ip netns exec rout1 ip addr add 192.168.100.254/24 dev tunnel.100
ip netns exec rout1 ip addr add 192.168.200.254/24 dev tunnel.200
ip netns exec rout1 ip link set dev l2tpeth0 mtu 1500

# Config tunnel rout2
ip netns exec rout2 ip l2tp add tunnel remote 172.16.1.253 local 172.16.2.253 encap ip tunnel_id 4000 peer_tunnel_id 3000
ip netns exec rout2 ip l2tp add session tunnel_id 4000 session_id 2000 peer_session_id 1000
ip netns exec rout2 ip link set l2tpeth0 up
ip netns exec rout2 ip a flush dev rout2-eth1
ip netns exec rout2 brctl addbr tunnel
ip netns exec rout2 brctl addif tunnel l2tpeth0
ip netns exec rout2 brctl addif tunnel rout2-eth1
ip netns exec rout2 ip link set tunnel up
ip netns exec rout2 ip link add link tunnel name tunnel.100 type vlan id 100
ip netns exec rout2 ip link set tunnel.100 up
ip netns exec rout2 ip link add link tunnel name tunnel.200 type vlan id 200
ip netns exec rout2 ip link set tunnel.200 up
ip netns exec rout2 ip addr add 192.168.100.253/24 dev tunnel.100
ip netns exec rout2 ip addr add 192.168.200.253/24 dev tunnel.200
ip netns exec rout2 ip link set l2tpeth0 mtu 1500

# # EX 4
# # Config tunnel GRETAP rout1
# sudo ip netns exec rout1 ip l add eoip1 type gretap remote 172.16.2.253 local 172.16.1.253 nopmtudisc
# sudo ip netns exec rout1 ip l set dev eoip1 up
# sudo ip netns exec rout1 brctl addbr tunnel
# sudo ip netns exec rout1 brctl addif tunnel eoip1
# sudo ip netns exec rout1 brctl addif tunnel rout1-eth1
# sudo ip netns exec rout1 ip l set tunnel up
# sudo ip netns exec rout1 ip l add link tunnel name tunnel.100 type vlan id 100
# sudo ip netns exec rout1 ip l set tunnel.100 up
# sudo ip netns exec rout1 ip l add link tunnel name tunnel.200 type vlan id 200                                     
# sudo ip netns exec rout1 ip l set tunnel.200 up
# sudo ip netns exec rout1 ip a add 192.168.100.254/24 dev tunnel.100
# sudo ip netns exec rout1 ip a add 192.168.200.254/24 dev tunnel.200

# # Config tunnel GRETAP rout2
# sudo ip netns exec rout2 ip l add eoip1 type gretap remote 172.16.1.253 local 172.16.2.253 nopmtudisc
# sudo ip netns exec rout2 ip l set dev eoip1 up
# sudo ip netns exec rout2 brctl addbr tunnel
# sudo ip netns exec rout2 brctl addif tunnel eoip1
# sudo ip netns exec rout2 brctl addif tunnel rout2-eth1
# sudo ip netns exec rout2 ip l set tunnel up
# sudo ip netns exec rout2 ip l add link tunnel name tunnel.100 type vlan id 100
# sudo ip netns exec rout2 ip l set tunnel.100 up
# sudo ip netns exec rout2 ip l add link tunnel name tunnel.200 type vlan id 200                                     
# sudo ip netns exec rout2 ip l set tunnel.200 up
# sudo ip netns exec rout2 ip a add 192.168.100.253/24 dev tunnel.100
# sudo ip netns exec rout2 ip a add 192.168.200.253/24 dev tunnel.200


# # EX 6
# Provide Internet access through the internet switch
ip l add veth0 type veth peer name internet-real
ovs-vsctl add-port internet internet-real
ip l set dev internet-real up
ip l set dev veth0 up
ip a add dev veth0 10.87.0.254/24

# Config the routing tables for the routers
ip netns exec routA ip r add default via 10.87.0.254 dev routA-eth1
ip netns exec rout1 ip r add default via 172.16.1.254 dev rout1-eth0

# Config the routing table of the Linux machine
sysctl net.ipv4.conf.all.forwarding=1
ip r add 172.16.1.0/24 via 10.87.0.1 dev veth0
ip r add 172.16.2.0/24 via 10.87.0.2 dev veth0

iptables -t nat -A POSTROUTING -o wlo1 -j MASQUERADE
ip netns exec rout1 iptables -t nat -A POSTROUTING -o rout1-eth0 -j MASQUERADE
# ip netns exec rout2 iptables -t nat -A POSTROUTING -o rout2-eth0 -j MASQUERADE
ip netns exec rout2 iptables -t nat -A PREROUTING -i rout2-eth1 -s 192.168.100.0/24 -j DNAT --to-destination 192.168.100.254
# ip netns exec rout2 iptables -t nat -A PREROUTING -i rout2-eth1 -s 192.168.200.0/24 -j DNAT --to-destination 192.168.200.254
# ip netns exec rout1 iptables -t nat -i l2tpeth0 -A PREROUTING -j MASQUERADE